<?php
// module/Feedback/view/feedback/feedback/delete.phtml:

$title = 'Delete feedback';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($feedback->title); ?>' by
    '<?php echo $this->escapeHtml($feedback->artist); ?>'?
</p>
<?php
$url = $this->url('feedback', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $feedback->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>
